/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "msg.h"

bool_t
xdr_InitInp (XDR *xdrs, InitInp *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->mynode))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->mypid))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_RequestRet (XDR *xdrs, RequestRet *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->size))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->valid))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_MallocInp (XDR *xdrs, MallocInp *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->name, ~0))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->size))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_RemoteInp (XDR *xdrs, RemoteInp *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->name, ~0))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->IsRead))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_NetworkInp (XDR *xdrs, NetworkInp *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->name, ~0))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->NetOp))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->mynode))
		 return FALSE;
	return TRUE;
}
