/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "msg.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

enum clnt_stat 
init_1(InitInp *argp, void *clnt_res, CLIENT *clnt)
{
	return (clnt_call(clnt, INIT,
		(xdrproc_t) xdr_InitInp, (caddr_t) argp,
		(xdrproc_t) xdr_void, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
malloc_1(MallocInp *argp, int *clnt_res, CLIENT *clnt)
{
	return (clnt_call(clnt, MALLOC,
		(xdrproc_t) xdr_MallocInp, (caddr_t) argp,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
request_1(char **argp, RequestRet *clnt_res, CLIENT *clnt)
{
	return (clnt_call(clnt, REQUEST,
		(xdrproc_t) xdr_wrapstring, (caddr_t) argp,
		(xdrproc_t) xdr_RequestRet, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
remoterdwr_1(RemoteInp *argp, int *clnt_res, CLIENT *clnt)
{
	return (clnt_call(clnt, REMOTERDWR,
		(xdrproc_t) xdr_RemoteInp, (caddr_t) argp,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
networkop_1(NetworkInp *argp, char **clnt_res, CLIENT *clnt)
{
	return (clnt_call(clnt, NETWORKOP,
		(xdrproc_t) xdr_NetworkInp, (caddr_t) argp,
		(xdrproc_t) xdr_wrapstring, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
free_1(char **argp, int *clnt_res, CLIENT *clnt)
{
	return (clnt_call(clnt, FREE,
		(xdrproc_t) xdr_wrapstring, (caddr_t) argp,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}
