/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "msg.h"

bool_t
xdr_input (XDR *xdrs, input *objp)
{
	register int32_t *buf;


	if (xdrs->x_op == XDR_ENCODE) {
		buf = XDR_INLINE (xdrs, 6 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_int (xdrs, &objp->you))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->me))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->num_nodes))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->lock_number))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->seq))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->release))
				 return FALSE;
		} else {
			IXDR_PUT_LONG(buf, objp->you);
			IXDR_PUT_LONG(buf, objp->me);
			IXDR_PUT_LONG(buf, objp->num_nodes);
			IXDR_PUT_LONG(buf, objp->lock_number);
			IXDR_PUT_LONG(buf, objp->seq);
			IXDR_PUT_LONG(buf, objp->release);
		}
		return TRUE;
	} else if (xdrs->x_op == XDR_DECODE) {
		buf = XDR_INLINE (xdrs, 6 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_int (xdrs, &objp->you))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->me))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->num_nodes))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->lock_number))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->seq))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->release))
				 return FALSE;
		} else {
			objp->you = IXDR_GET_LONG(buf);
			objp->me = IXDR_GET_LONG(buf);
			objp->num_nodes = IXDR_GET_LONG(buf);
			objp->lock_number = IXDR_GET_LONG(buf);
			objp->seq = IXDR_GET_LONG(buf);
			objp->release = IXDR_GET_LONG(buf);
		}
	 return TRUE;
	}

	 if (!xdr_int (xdrs, &objp->you))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->me))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->num_nodes))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->lock_number))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->seq))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->release))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_output (XDR *xdrs, output *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->seq))
		 return FALSE;
	return TRUE;
}
